 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/secrets.toml b/secrets.toml
index 096bae111a869125518bab4189906c569625b7ec..693c226d5405c779851369726cbac573f4abbdcb 100644
--- a/secrets.toml
+++ b/secrets.toml
@@ -1,5 +1,8 @@
 TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
 TELEGRAM_CHAT_ID = "your-telegram-chat-id"
 ALPACA_API_KEY = "your-alpaca-api-key"
 ALPACA_SECRET_KEY = "your-alpaca-secret-key"
 ALPACA_ENDPOINT = "https://paper-api.alpaca.markets"
+FINNHUB_API_KEY = "your-finnhub-key"
+[USERS]
+admin = "password"
 
EOF
)
